all:
 vars:
  ansible_user: admin
  ansible_password: "{{vault_ansible_password}}"
  ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
prod:
  hosts:
    client:
      ansible_host: 10.0.7.6
      ansible_sudo_pass: admin
 

